### ISSUE TITLE
ganesha crash in svc_release_it v1.6.2

### ISSUE THREAD

**Issue by fangyuxiangGL** [nfs-ganesha/ntirpc#145]
Thread 49 (Thread 0x7fa2e26ed700 (LWP 20697)):
#0  0x00007fa0c0000478 in ?? ()
#1  0x00007fa3469b4307 in svc_release_it (flags=0, line=218, tag=<synthetic pointer>, xprt=0x7fa0c06dab80) at /home/fyx/libntirpc-1.6.2/ntirpc/rpc/svc.h:417
#2  svc_ioq_write (xprt=0x7fa0c06dab80, xioq=0x7fa0c0272770, ifph=0x7fa346bc9260 <ioq_ifqh>) at /home/fyx/libntirpc-1.6.2/src/svc_ioq.c:218
#3  0x00007fa3469b4737 in work_pool_thread (arg=0x7fa2a4001ed0) at /home/fyx/libntirpc-1.6.2/src/work_pool.c:176
#4  0x00007fa346dd96ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007fa34636b82d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by fangyuxiangGL** [comment]
@dang @was4 

could you please have a look?

**Comment by was4** [comment]
On 8/28/18 11:16 PM, fangyuxiang wrote:
>> home/fyx/libntirpc-1.6.2/src/svc_ioq.c:218
[...]
> @dang <https://github.com/dang> @was4 <https://github.com/was4>
> 
> could you please have a look?
> 
Could you please try again with ntirpc-1.6.3?  I know I'd
submitted a number of patches against next that might affect this.
What I don't know (without looking) is which ones were backported,
not how badly they were mangled during the backport.

**Comment by ffilz** [comment]
I'm going to close this as it is years old and V1.6 is long out of support (we are now supporting V5.x and working V6).
