### ISSUE TITLE
[Reopen #153] Ganesha crashed after running delegations cases for pynfs

### ISSUE THREAD

**Issue by thotz** [nfs-ganesha/ntirpc#168]
On latest master I am still seeing crash while running pynfs test suite for delegations during clean part
If needed I can bisect which version cause the issue recreated again

(gdb) bt
#0 0x0000000000000000 in ?? ()
#1 0x00007fa8b185bf3e in svc_release_it (xprt=0x7fa850000c90, flags=0, tag=0x7fa8b18837c0 <func.8331> "clnt_vc_destroy", line=462) at /root/nfs-ganesha/src/libntirpc/ntirpc/rpc/svc.h:440
#2 0x00007fa8b185cd0b in clnt_vc_destroy (clnt=0x7fa850000b70) at /root/nfs-ganesha/src/libntirpc/src/clnt_vc.c:462
#3 0x000000000044107a in clnt_release_it (clnt=0x7fa850000b70, flags=0, tag=0x579b80 <func.22987> "_nfs_rpc_destroy_chan", line=628) at /root/nfs-ganesha/src/libntirpc/ntirpc/rpc/clnt.h:319
#4 0x0000000000441110 in clnt_destroy_it (clnt=0x7fa850000b70, tag=0x579b80 <func.22987> "_nfs_rpc_destroy_chan", line=628) at /root/nfs-ganesha/src/libntirpc/ntirpc/rpc/clnt.h:341
#5 0x0000000000444629 in _nfs_rpc_destroy_chan (chan=0x7fa860010b18) at /root/nfs-ganesha/src/MainNFSD/nfs_rpc_callback.c:628
#6 0x0000000000445297 in nfs_rpc_destroy_chan (chan=0x7fa860010b18) at /root/nfs-ganesha/src/MainNFSD/nfs_rpc_callback.c:864
#7 0x00000000004d7e4f in nfs_client_id_expire (clientid=0x7fa860010a70, make_stale=false) at /root/nfs-ganesha/src/SAL/nfs4_clientid.c:1099
#8 0x000000000044a301 in reap_hash_table (ht_reap=0x1505920) at /root/nfs-ganesha/src/MainNFSD/nfs_reaper_thread.c:109
#9 0x000000000044aaa4 in reaper_run (ctx=0x1535a80) at /root/nfs-ganesha/src/MainNFSD/nfs_reaper_thread.c:232
#10 0x000000000051762e in fridgethr_start_routine (arg=0x1535a80) at /root/nfs-ganesha/src/support/fridgethr.c:552
#11 0x00007fa8b0022dd5 in start_thread (arg=0x7fa855ffb700) at pthread_create.c:307
#12 0x00007fa8af721ead in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) f 1
#1 0x00007fa8b185bf3e in svc_release_it (xprt=0x7fa850000c90, flags=0, tag=0x7fa8b18837c0 <func.8331> "clnt_vc_destroy", line=462) at /root/nfs-ganesha/src/libntirpc/ntirpc/rpc/svc.h:440
440 (*(xprt)->xp_ops->xp_destroy)(xprt, flags, tag, line);
(gdb) p *(xprt)->xp_ops
$1 = {xp_recv = 0xbaadf00d, xp_stat = 0x861, xp_decode = 0x7fa850033190, xp_reply = 0x7fa850000c80, xp_checksum = 0x0, xp_destroy = 0x0, xp_control = 0xffffffffffffffff, xp_free_user_data = 0x0}

**Comment by dang** [comment]
I don't seem to have gotten an email about this.  I'm sorry I missed it.  Can you bisect?  That would help a lot.

**Comment by ffilz** [comment]
This is old and no response from the reporter. Closing as wontfix.
