### ISSUE TITLE
Replacement for xdr_[u_]char (backwards compatibility with libtirpc)

### ISSUE THREAD

**Issue by pevik** [nfs-ganesha/ntirpc#200]
Commit d079d529 removed `xdr_[u_]char`. Is there any replacement for them? Or isn't backwards compatibility with libtirpc achievable anyway, so there is no point to have them? (e.g. kerberos has [gssrpc/rename.h](https://github.com/krb5/krb5/blob/master/src/include/gssrpc/rename.h), which allows some compatibility)

**Comment by dang** [comment]
You should be able to use xdr_get[u]int8 and xdr_put[u]int8

**Comment by pevik** [comment]
Thanks for info, I'll have a look. I guess ntirpc goal to be replacement for libtirpc, right? But is it also API compatible (is it drop-in replacement without requiring the changes?)

My question is whether LTP TI-RPC tests are also applicable for ntirpc. 

And also whether LTP is a best place for these tests (IMHO API tests should belong to the project, but if APIs of these 2 libraries are the same or very similar it'd be good to have them on single git repository).

\+ feel free to comment on these questions on LTP ML https://lists.linux.it/pipermail/ltp/2020-January/015143.html

**Comment by dang** [comment]
ntirpc is intended to be a replacement for tirpc for projects that need low latency, high throughput, and multithreading.  It's not, however, intended to be a drop in replacement;  It's threading model, for example, is not compatible.  We'd welcome more testing.  I'm not sure where the best place for it is, however.

**Comment by ffilz** [comment]
Closing this as yes, libntirpc is a replacement for libtirpc, but is not intended to be API compatible.
