### ISSUE TITLE
frequent crashes in authgss_hash.c

### ISSUE THREAD

**Issue by koen-struyve** [nfs-ganesha/ntirpc#205]
Seen on nfsganesha version 2.8.2, ntirpc version 1.8.0, running on ubuntu 16.04.

We see two different types of crashes occurring, on one test system we almost daily the following type of crash.

```
/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2(gss_inquire_context+0x98) [0x7f0c55a11ea4]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x2c892) [0x7f0c5679d892]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x219ec) [0x7f0c567929ec] 
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x2a118) [0x7f0c5679b118]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f0c56f8a6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f0c56ab841d]
```

The call to gss_inquire_context is the one at https://github.com/nfs-ganesha/ntirpc/blob/v1.8.0/src/authgss_hash.c#L251 , called from https://github.com/nfs-ganesha/ntirpc/blob/v1.8.0/src/authgss_hash.c#L286 .

We also saw the following stack trace:

```
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x2bfe0) [0x7f10d50c2fe0]
nfsganesha/bin/../lib/libntirpc.so.1.8(opr_rbtree_insert+0x20) [0x7f10d50a81a0]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x2c52f) [0x7f10d50c352f]
nfsganesha/bin/../lib/libntirpc.so.1.8(_svcauth_gss+0x845) [0x7f10d50c62f5]
nfsganesha/bin/../lib/libganesha_nfsd.so.2.8(+0x31bc5) [0x7f10d5af7bc5]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x22c71) [0x7f10d50b9c71]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x2116d) [0x7f10d50b816d]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x217aa) [0x7f10d50b87aa]
nfsganesha/bin/../lib/libntirpc.so.1.8(+0x2a118) [0x7f10d50c1118]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f10d58b06ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f10d53de41d]
```

In the code this corresponds with https://github.com/nfs-ganesha/ntirpc/blob/v1.8.0/src/authgss_hash.c#L87 , directly preceding to this crash we saw in the ganesha logs:

```
 [svc_2653] nfs_rpc_process_request :DISP :INFO :Could not authenticate request... rejecting with AUTH_STAT=RPCSEC_GSS_CREDPROBLEM
```

**Comment by dang** [comment]
I suspect this is dbfec91067a5e755c1225dbada1f457115caec5b fixed in ntirpc 3.0.  There hasn't been another ntirpc 1.8 release since then.  We can include this fix in the next 2.8/1.8, which should be fairly soon.

**Comment by koen-struyve** [comment]
Thanks for the quick reply. I will cherry-pick this commit and see if the problem persists.

**Comment by koen-struyve** [comment]
This does seem to resolve the issue, closing this ticket.
