### ISSUE TITLE
[RFE] Support HAProxy's PROXY protocol

### ISSUE THREAD

**Issue by gouthampacha** [nfs-ganesha/ntirpc#252]
To protect from node and service failures, it is desirable to deploy NFS-Ganesha in active/active highly available configurations. The Ceph community has designed an architecture which puts one or more nfs-ganesha servers behind an ingress service. The ingress service comprises of haproxy and keepalived [1]. 

While the solution works well, it is less secure because users cannot enforce client IP restrictions in this architecture. HAProxy terminates client connections and NFS-Ganesha only sees the traffic as originating from the HAProxy node/s, which would invalidate any IP address specified in the CLIENT block of NFS-Ganesha export configs. 

It would be feasible to use the IP address of the HAProxy node in the CLIENT block, but this will allow everyone with access to the HAProxy node to have access to the filesystem exported. 

One solution could be supporting the PROXY protocol [2][3] where packets originating from HAProxy would have an additional header that contains the source client's IP address. NFS-Ganesha could parse this IP address and return information directly to it.

Open source projects that are benefactors of this solution would include Ceph, OpenStack Manila and Rook among a host of others.

[1] https://docs.ceph.com/en/latest/cephadm/services/nfs/
[2] https://www.haproxy.com/blog/haproxy/proxy-protocol/ 
[3] http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Comment by ffilz** [comment]
Capturing some of what I am reading about the protocol:

Version 1: ASCII header
Version 2: Binary Header

Do we think we need to support version 1 at all?

It looks like the header comes once at the beginning of the connection. There would be a connection per client.

It looks like we should always expect HA proxy if it's in use. At least for connections from the HA proxy. Do we need to support non-HA proxy connections alongside HA proxy connections? If so, we need to configure which IP addresses to expect HA proxy from, otherwise we enable HA proxy or not.

**Comment by ffilz** [comment]
I've opened a Google Doc to start collecting design thoughts.

https://docs.google.com/document/d/1orjNjtEeeyRrgvbQuFU5BdsCnZG9gF3MymDCZl-gOTs/edit?usp=sharing

If you want to be able to comment directly on the document, please request access via Google Docs.

**Comment by ffilz** [comment]
And I just looked at the pre-mdcache code (V2.4-dev.15) and I see how the old pin refs work. The suspicious code around the list management is the result of incorrect translation from pin ref to regular ref count. The lock_entry refcount is sufficient for the current scheme so we don't need the extra list management ref count manipulation. I'm going to add a patch to remove it...

**Comment by ffilz** [comment]
Pull request

https://github.com/nfs-ganesha/ntirpc/pull/268

**Comment by ktdreyer** [comment]
Is there more work to do here, or can we close this now?

**Comment by ffilz** [comment]
I was hoping for some verification before closing. If someone (besides me) has verified it's working, then we can close it.

**Comment by gouthampacha** [comment]
> I was hoping for some verification before closing. If someone (besides me) has verified it's working, then we can close it.

I did some testing with Ceph; ceph orchestrator is going to support for this feature via https://github.com/ceph/ceph/pull/50614.

My test results are here: https://gist.github.com/gouthampacha/3417141d919bb541e03882fae4f776ce 

This works great and solves the original issue we had! Thank you @ffilz

**Comment by ffilz** [comment]
Closing this
