### ISSUE TITLE
nfs mishandles reference counts: xp_refcnt

### ISSUE THREAD

**Issue by manishladdha** [nfs-ganesha/ntirpc#265]
ganesha was accepting the connection but then immediately closing it. Based on logs and stracing, we feel the accept is returning a fd that is already in the tree:

svc_vc_rendezvous calls makefd_xprt on accepted fd

makefd_xprt calls svc_xprt_lookup

svc_xprt_lookup finds the fd in opr_rbtree_lookup, increments the reference count on it, and returns it (the flags must be INITIALIZED and not DESTROYED) makefd_xprt finds it is already INITIALIZED and returns it

svc_vc_rendezvous finds it's not INITIAL, closes the fd, and returns, without decrementing the reference count

When the client attempts to reconnect, accept often gives the same fd, guaranteeing the same sequence over again. Eventually when some other connection is closed, accept returns a different fd not in the tree and things work. The end result is long random client hangs.

Can you please help as to what could have caused this behavior ?

**Comment by manishladdha** [comment]
@dang
Good day, Just wanted to check if you had a chance to look into this  ?

**Comment by dang** [comment]
I'm sorry, I haven't had a chance yet.  I'll try to get to it this week.

**Comment by manishladdha** [comment]
@dang 
Could you please help us out with your analysis, and suggest a solution/workaround.

**Comment by manishladdha** [comment]
@dang 
gentle reminder

**Comment by dang** [comment]
Can you try the top commit on this branch: https://github.com/dang/ntirpc/tree/i265

**Comment by manishladdha** [comment]
Hi @dang 
Based on the commit comments, was the new code supposed to be after makefd_xprt() call ?

newxprt = makefd_xprt(fd, req_xd->sx_dr.sendsz, req_xd->sx_dr.recvsz,
			      &si, SVC_XPRT_FLAG_CLOSE);
 if (newxprt) {
			SVC_DESTROY(newxprt);
			/* Was never added to epoll */
			SVC_RELEASE(newxprt, SVC_RELEASE_FLAG_NONE);
                      return (XPRT_DIED);
      		  } 
else if ((!newxprt) || (!(newxprt->xp_flags & SVC_XPRT_FLAG_INITIAL))) {
		close(fd);
		return (XPRT_DIED);
	}

**Comment by dang** [comment]
You're right, new commit pushed.

**Comment by manishladdha** [comment]
We have been trying to reproduce it locally with and without the code changes, but the issue still does not hit considering this being a corner case.
We will now run our regression suites to confirm if everything is OK, and this should take around 3-4 days.

We will be sharing the status as soon as we complete our tests.

**Comment by ffilz** [comment]
Looking over the code, it looks correct to me so let's go forward with merging this fix.

**Comment by manishladdha** [comment]
Hi,
Test results are positive for all the regression runs.

Thank you @dang for your help.

**Comment by ffilz** [comment]
Shall we close this?
