### ISSUE TITLE
Q: Why is RPC request(record) split into multiple fragments?

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/ntirpc#306]
I find that one RPC request is split into multiple fragments when it is sent and received(from the function named svc_vc_recv in src/svc_vc.c).  We need many recv() syscalls to compose the whole RPC request. Is it not enough to send and receive the request as a whole with only one header? I'm curious about the considerations of the fragment/record design. 

> /*
>  * A record is composed of one or more record fragments.
>  * A record fragment is a four-byte header followed by zero to
>  * 2**32-1 bytes.  The header is treated as a long unsigned and is
>  * encode/decoded to the network via htonl/ntohl.  The low order 31 bits
>  * are a byte count of the fragment.  The highest order bit is a boolean:
>  * 1 => this fragment is the last fragment of the record,
>  * 0 => this fragment is followed by more fragment(s).
>  *
>  * The fragment/record machinery is not general;  it is constructed to
>  * meet the needs of xdr and rpc based on tcp.
>  */

https://github.com/nfs-ganesha/ntirpc/blob/eb1937029b2d7425bd8517dd2f5bab2f3cdd9a03/src/svc_vc.c#L100

**Comment by ffilz** [comment]
Is your client sending multiple fragments? Where are you observing this?

I did notice that pynfs does break a request up into a number of small records such that very large write has more than 1024 fragments and broke the zero copy use of iovec...

**Comment by zhitaoli-6** [comment]
I find that if there is 10 GB data in writing, then nfs-ganesha takes up 20GB memory. I suspect that it is because `xdr_WRITE3args()` in DECODE requests from XDR allocates contiguous memory and copies the non-contiguous iovec from XDR. There exists double space amplification in memory usage for nfs write requests. 

I do care about memory usage of nfs-ganesha. Maybe whether the nfs request is split into multiple fragments or not, XDR has to use non-contiguous iovec to receive from TCP socket. 

Am I right?  Is it possible to avoid the memory allocated and copied here?

**Comment by zhitaoli-6** [comment]
> Is your client sending multiple fragments? Where are you observing this?

I don't observe fragments. I'm just looking at the implementation and have this question.

**Comment by ffilz** [comment]
> I find that if there is 10 GB data in writing, then nfs-ganesha takes up 20GB memory. I suspect that it is because `xdr_WRITE3args()` in DECODE requests from XDR allocates contiguous memory and copies the non-contiguous iovec from XDR. There exists double space amplification in memory usage for nfs write requests.
> 
> I do care about memory usage of nfs-ganesha. Maybe whether the nfs request is split into multiple fragments or not, XDR has to use non-contiguous iovec to receive from TCP socket.
> 
> Am I right? Is it possible to avoid the memory allocated and copied here?

Yes, indeed. See this Ganesha patch set:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1195024

Note we will still make a copy if the incoming request is in more than 1024 fragments (well, specifically, if the write data occupies more than 1024 fragments).

The Linux client at least just uses a single fragment for the entire request and the above patch set (hopefully to be merged this week) will indeed reduce memory allocation by half.

**Comment by zhitaoli-6** [comment]
I believe this patch can work. Thanks for your reply.
