### ISSUE TITLE
Race between svc_rqst_hook_events() and svc_rqst_handle_event().

### ISSUE THREAD

**Issue by pradeepthomas** [nfs-ganesha/ntirpc#56]
I'm hitting an issue with ganesha.nfsd with libntirpc which seems to 
have been caused by a recent change in libntirpc. Here is the sequence:

. NFS client does a mount.
. mount sends a NFS_NULL message to NFS v4 server.
. As part of connection establishment, libntirpc does accept() and FD
  is added to epoll FDs using epoll_ctl(). Once epoll_ctl() succeeds,
  it sets a bit in xprt->xp_flags (SVC_XPRT_FLAG_ADDED).
  See libntirpc/src/svc_rqst.c:svc_rqst_hook_events()
. In the meantime, epoll_wait() could return the FD (before the bit 
  gets set). This causes svc_rqst_handle_event() to ignore the latest
  event and the socket receive buffer is not read.
. The client that did the mount hangs till it times out.

The check for SVC_XPRT_FLAG_ADDED seems to be added few months ago
as part of the commit below:
https://github.com/nfs-ganesha/ntirpc/commit/fa08574571eebbaac883fdbed9138cc33fa1432e

Could someone please take a look to confirm the race and suggest the 
right fix to make?

Is removing the check for SVC_XPRT_FLAG_ADDED in svc_rqst_handle_event() the right fix?

Thanks

**Comment by dang** [comment]
Bill is reworking the receive loops, and this may not be an issue anymore with HEAD of libntirpc.  Adding him to check.

**Comment by dang** [comment]
This is still an issue, thanks for the report.  Bill will work on a fix.

**Comment by was4** [comment]
Excellent report. Kudos. Old logic mistake exposed by newer usage of existing flags. Will backport the V1.6 fix, or a facsimile thereof. Do you have a public email address you'd like to credit? For now, I'm just saying "Reported-by: Pradeep Thomas".

**Comment by was4** [comment]
Welcome. We have a conference call each week. Please join!

NFS Ganesha Conference Call
--
Location: | USA phone: 1-866-951-1151, Room Number: 2500620, France : 0 805 541 041, Germany : 0 800 723 5118, Israel: +972 1809212874, India: +91 0008008521444
When: | Occurs every Tuesday effective 1/19/16 from 11:30 AM to 12:30 PM (EDT)
