### ISSUE TITLE
Clarification: Compatibility with sunrpc / libtirpc?

### ISSUE THREAD

**Issue by akhuettel** [nfs-ganesha/ntirpc#79]
Dear ntirpc authors, 

it would be useful to have some statement whether
* ntirpc is source code compatible with sunrpc and/or libtirpc (and inhowfar)
* and whether you intend to keep it like this or want to evolve the API. 

Sorry if the answers to these questions seem obvious to you & thanks in advance!

**Comment by mattbenjamin** [comment]
Hi Andreas,

1. Not sure who I am addressing.  Are you a distro maintanier?  Please clarify.
2. ntirpc is actively maintained as the ONC RPC framework for nfs-ganesha and related projects, it's goals and features differ from those of the aforementioned implementations (e.g., need for thread-safe concurrency, bi-directional RPC on TCP, &c), and in particular, we do not currently make any api or even abi stability promises independent of those projects.  If you'd like to consume ntirpc for a project or product, we welcome you to engage with the project via the nfs-ganesha community.
Matt

Matt

**Comment by akhuettel** [comment]
about 1) 
I'm Gentoo developer and have recently become glibc maintainer there. I'm trying to decide how much we want to make the RPC implementation exchangeable. The two options that I see is 
* either, with glibc-2.26 drop sunrpc and migrate everyone to libtirpc, 
* or offer three implementations (sunrpc up to glibc-2.25, libtirpc, ntirpc), have package maintainers decide which ones their package supports

Obviously the second only makes sense if there is a non-negligible amount of packages that can build both against libtirpc and ntirpc. I have started setting up a testing framework for that, but am not sure yet how much work I should put into that.

about 2)
this kind of answers the question. I understand it's a specialized project and will slowly migrate away from compatibility - correct?

**Comment by mattbenjamin** [comment]
#1 ok, makes sense--basically, if you are following Red Hat and Oracle (?), you are probably following your path 1 (migrating to libtirpc) for your general runtime and linkage support for (e.g.) rpcbind;  if you want to package nfs-ganesha, you additionally need ntirpc (which does not conflict with either of the others)
#2 yes, exactly

Matt

**Comment by akhuettel** [comment]
OK thanks a lot!

(We tend to get the "specialists" who want to force square pegs into round holes, so having confirmation that putting lots of effort into something makes no sense is always good... otherwise I get a dozen e-mails "but why don't you support that?!") :)
